# Generated by Django 3.2.12 on 2022-03-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('statement', models.TextField(blank=True)),
                ('algo', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('first_statement', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('inputType', models.CharField(blank=True, max_length=100, null=True)),
                ('outputType', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ManyToManyField(blank=True, to='ques.Company')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ques.difficulty')),
                ('methods', models.ManyToManyField(blank=True, related_name='questions_methods', to='ques.Method')),
                ('typeOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ques.type')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_method', to='ques.question'),
        ),
    ]
