# Generated by Django 3.2.12 on 2022-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
